### ISSUE TITLE
Move to ruby-rdf namespace?

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/ldp_testsuite_wrapper#1]
@cbeer what do you think about releasing this into the public domain and moving it to the `ruby-rdf` namespace?

**Comment by cbeer** [comment]
👌 with me.

**Comment by no-reply** [comment]
If you pass me the appropriate permissions, I can move the repository.

**Comment by cbeer** [comment]
Ok; I've moved this into a new organization where you should have the right privileges.
